<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_search google or type a url</name>
   <tag></tag>
   <elementGuidId>b155e5c8-a9d7-4ebc-bf71-9447157bc5e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wM6W7d > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jZ2SBf']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0182d46-aee7-4a69-96b0-5b255ffb722d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search google or type a url</value>
      <webElementGuid>c028b1a2-e55f-4aa7-acac-0ac1b4c30898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jZ2SBf&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>bc0bcf4b-1ae4-4660-bb7d-0a684ba8f680</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jZ2SBf']/div/span</value>
      <webElementGuid>6dc8a61e-452f-48dd-91d6-7ef1dd5f53f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::span[11]</value>
      <webElementGuid>23161791-c789-43da-8d8a-0bde08e6fdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::span[11]</value>
      <webElementGuid>4bf9408c-e20e-41b1-95d2-44dd97c1b2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more'])[1]/preceding::span[3]</value>
      <webElementGuid>d86716c2-851c-41ba-bf26-a0ab12d14789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='search google']/parent::*</value>
      <webElementGuid>7dbedb16-e273-4051-b4d5-9d83a29b7b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>c3e88cfd-7a88-4233-84c7-654ff1b97f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'search google or type a url' or . = 'search google or type a url')]</value>
      <webElementGuid>9254660f-8820-4ddc-8397-4c3033dc96e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
