<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter last name</name>
   <tag></tag>
   <elementGuidId>e8548b7f-29ec-4795-b6ed-f2f58bc4f3a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lastname-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lastname-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>81879ee4-a0b6-4cbb-9c18-96ded7da213b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname-error</value>
      <webElementGuid>76e204f7-41c1-454d-aba4-9e36d3c4c848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>597db222-840f-4fc5-a703-373e43a90229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>bf1dd78a-1362-46df-a154-20d119653964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter last name</value>
      <webElementGuid>74977a72-994f-4146-b32d-81fa72db95eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastname-error&quot;)</value>
      <webElementGuid>f4e5c6e0-ac6a-4255-9849-a15eb799213c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lastname-error']</value>
      <webElementGuid>1b38b5a3-a7a9-461d-a354-a140bf069cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='common-form']/div[2]/label</value>
      <webElementGuid>f1415d17-e58c-46b6-8df0-542bab03b7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter first name'])[1]/following::label[1]</value>
      <webElementGuid>c9899b56-0da5-4a4f-86fd-e3799f0a79aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='next'])[2]/following::label[2]</value>
      <webElementGuid>d82614ff-c137-4270-a157-ccefdbb4f753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a valid email'])[1]/preceding::label[1]</value>
      <webElementGuid>813eaff9-4b58-4e33-b69c-02c7fa9fbc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter phone number'])[1]/preceding::label[2]</value>
      <webElementGuid>6a6a6b3e-8d34-4b4e-a19b-5ce505c5b7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter last name']/parent::*</value>
      <webElementGuid>049251c0-4228-480f-824f-c4e0cc9bf775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>c049aba2-0838-4314-b9ed-364e4cd8e4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lastname-error' and (text() = 'Please enter last name' or . = 'Please enter last name')]</value>
      <webElementGuid>d0bba77e-51a0-45c2-a032-dc058ded43c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
