<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter a valid email</name>
   <tag></tag>
   <elementGuidId>68c5e1e3-1cce-4715-9b29-cb8a097b25e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='email-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4eb25a20-fbfb-46d7-844f-a17a24dc3b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-error</value>
      <webElementGuid>d61353d8-80e0-4506-91c0-30d11427a6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>6a4bb4c6-2ab3-4376-a8e2-7c191c084de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>695cd8e5-1578-435f-8db4-43b7d55a5877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid email</value>
      <webElementGuid>88f23923-f80e-4265-aa41-80d9b0bd60ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-error&quot;)</value>
      <webElementGuid>a1734a49-213c-45fa-8f23-fd95b908a487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='email-error']</value>
      <webElementGuid>41c54a8c-712f-4646-8236-71effcdc3068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='common-form']/div[3]/label</value>
      <webElementGuid>b5984c42-16db-41bf-9cb1-eb5b76ffae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter last name'])[1]/following::label[1]</value>
      <webElementGuid>17c78ff0-666e-4eb1-ace0-b2bbfc4187cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter first name'])[1]/following::label[2]</value>
      <webElementGuid>cd33194d-5745-4b27-acbe-0149cf2ab392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter phone number'])[1]/preceding::label[1]</value>
      <webElementGuid>ec63ee52-0228-495c-9bb3-526fec08a2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill the required field'])[1]/preceding::label[2]</value>
      <webElementGuid>82ef2027-147d-48a9-9f1b-1076341b9598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter a valid email']/parent::*</value>
      <webElementGuid>aec31140-0969-44ae-aaf4-fc7e93a225f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label</value>
      <webElementGuid>f09dbef2-d1a6-4f7f-a15b-054a504bb3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'email-error' and (text() = 'Please enter a valid email' or . = 'Please enter a valid email')]</value>
      <webElementGuid>e16003ae-f16e-497c-ad57-b4e6ecceb0a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
