<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter phone number</name>
   <tag></tag>
   <elementGuidId>4e2449ba-89ff-4852-8715-14d534ca7375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>V</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phonenumber-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>255f223d-da5e-40fb-9fa4-1158df736591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phonenumber-error</value>
      <webElementGuid>b82087b7-ec61-492f-b355-961ca7759332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>07e1ae08-ab20-4432-92f1-8df8d54b2c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>606be6c2-6f3f-43ff-acce-74a95edcd884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter phone number</value>
      <webElementGuid>1e4b8aac-4b5e-42f3-8730-2344d38e64e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phonenumber-error&quot;)</value>
      <webElementGuid>bad39676-4622-4a90-858a-aec5d4b2e774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='phonenumber-error']</value>
      <webElementGuid>36f01c06-e213-4ae0-b668-5f13991fe657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='common-form']/div[4]/label</value>
      <webElementGuid>561602a0-95c5-4098-a3dc-6554d0145eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a valid email'])[1]/following::label[1]</value>
      <webElementGuid>964cf434-110f-4d13-bf42-39fec679d727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter last name'])[1]/following::label[2]</value>
      <webElementGuid>4d8e7bb5-6fde-47fe-bad5-54e5a4044ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill the required field'])[1]/preceding::label[1]</value>
      <webElementGuid>b15a3673-1f85-4e78-af95-eb225284062f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please fill the required field'])[2]/preceding::label[2]</value>
      <webElementGuid>ca360ed8-af21-43a1-b87d-90efe6104850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter phone number']/parent::*</value>
      <webElementGuid>62cd08b9-1a2d-436d-967a-696d00b84575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>59e341ca-8391-468b-b8b5-ba2b88dc4656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'phonenumber-error' and (text() = 'Please enter phone number' or . = 'Please enter phone number')]</value>
      <webElementGuid>af3e0c38-0ed1-409e-a51f-71cdc1e81e2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
